version: '3'

services:
  backend_lab_2_2024:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URI_DEV: "${DATABASE_URI_DEV}"
      FLASK_APP: "app.py"
      PORT: "8082"
    ports:
      - "8082:8082"
    depends_on:
      - postgresLab_3

  postgresLab_3:
    image: postgres
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "5434:5432"
