import os

PROPAGATE_EXCEPTIONS = True
GLASK_DEBUG = True
DATABASE_ENV_URI_DEV = os.environ.get('DATABASE_URI_DEV')
DATABASE_ENV_URI_RELEASE = os.environ.get('DATABASE_URI_RELEASE')
if DATABASE_ENV_URI_DEV is None:
    SQLALCHEMY_DATABASE_URI = DATABASE_ENV_URI_RELEASE
else:
    SQLALCHEMY_DATABASE_URI = DATABASE_ENV_URI_DEV
SQLALCHEMY_TRACK_MODIFICATIONS = False
API_TITLE = "Cost Categories REST API"
API_VERSION = "v1"
